### PR TITLE
Update current.yml

### PR DESCRIPTION
**Pull request by csondes**
Please approve

### CODE REVIEW

**Comment by ckenst** [comment]
@csondes is this related to software testing? Based on the name it doesn't sound like it.

**Comment by csondes** [comment]
This is an academic conference about modelling languages and you can find test languges also in the list: UML, ASN.1, TTCN, SysML and URN. TTCN  is a testing language, and ASN.1 is a data description languages used in testing. In Model-driven development topics there are
 - systematic and automated testing and
 - model-based testing (MBT)

Approximately 20-25% of presentations is about testing, however you are right it's mainly about testing.

**Comment by csondes** [comment]
sorry:
it's mainly about modelling and not testing

**Comment by ckenst** [comment]
@csondes thanks for helping me understand. I think in this case, it probably doesn't fit the criteria we are going for. I appreciate the effort to help!

**Pull request closed without merging**
