### PR TITLE
Update current.yml

### PR DESCRIPTION
**Pull request by nscavalleri**
Argentesting was added

### CODE REVIEW

**Comment by ckenst** [comment]
@nscavalleri so close. What happened?

**Comment by nscavalleri** [comment]
I didn't know how to continue :-(

2018-03-20 0:58 GMT-03:00 Chris Kenst <notifications@github.com>:

**Comment by nscavalleri** [comment]
Thank you in advance!

2018-03-20 14:49 GMT-03:00 Chris Kenst <notifications@github.com>:

**Comment by ckenst** [comment]
The details look good, however the location in the list was wrong so I fixed it.

**Comment by nscavalleri** [comment]
you are a genius! Thank you

2018-03-20 15:32 GMT-03:00 Chris Kenst <notifications@github.com>:

**Pull request merged**
